import type { ComponentManifest } from './types.js';

const onPress = { name: 'onPress', type: 'action' as const, description: 'navigate / back / custom' };
const items = { name: 'items', type: 'binding' as const, description: 'data binding path, e.g. $state.cart.items' };

/** The built-in block library — 31 blocks covering the patterns the Annotator detects. */
export const BUILTINS: ComponentManifest[] = [
  // ── Navigation ────────────────────────────────────────────────
  {
    ref: 'oas/tab-bar',
    name: 'Tab Bar',
    description: 'Bottom tab navigation',
    patterns: ['tabbar'],
    props: [{ name: 'tabs', type: 'items', required: true }],
  },
  {
    ref: 'oas/nav-header',
    name: 'Navigation Header',
    description: 'Stack screen header with title and back button',
    patterns: ['navbar'],
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'showBack', type: 'boolean', default: true },
    ],
  },
  {
    ref: 'oas/drawer',
    name: 'Drawer Menu',
    description: 'Side drawer navigation',
    patterns: ['drawer'],
    props: [{ name: 'items', type: 'items', required: true }],
  },
  // ── Collections ───────────────────────────────────────────────
  {
    ref: 'oas/list',
    name: 'List',
    description: 'Vertical list of rows',
    patterns: ['list'],
    roles: ['list', 'feed', 'settings'],
    props: [items, { name: 'onItemPress', type: 'action' }],
    slots: ['item'],
  },
  {
    ref: 'oas/grid',
    name: 'Grid',
    description: 'Responsive card grid',
    patterns: ['grid'],
    roles: ['list', 'feed', 'search'],
    props: [items, { name: 'columns', type: 'number', default: 2 }, { name: 'onItemPress', type: 'action' }],
    slots: ['item'],
  },
  {
    ref: 'oas/carousel',
    name: 'Carousel',
    description: 'Horizontal swipeable cards',
    patterns: ['carousel'],
    props: [items],
    slots: ['item'],
  },
  {
    ref: 'oas/infinite-feed',
    name: 'Infinite Feed',
    description: 'Paginated infinite-scroll feed',
    patterns: ['list'],
    roles: ['feed'],
    props: [items, { name: 'pageSize', type: 'number', default: 20 }],
    slots: ['item'],
  },
  // ── Content ───────────────────────────────────────────────────
  {
    ref: 'oas/card',
    name: 'Card',
    description: 'Content card with header/body/footer slots',
    patterns: ['card'],
    props: [onPress],
    slots: ['header', 'body', 'footer'],
  },
  {
    ref: 'oas/detail-header',
    name: 'Detail Header',
    description: 'Hero image + title block for detail screens',
    patterns: ['card', 'navbar'],
    roles: ['detail'],
    props: [
      { name: 'title', type: 'binding', required: true },
      { name: 'imageUrl', type: 'binding' },
      { name: 'subtitle', type: 'binding' },
    ],
  },
  {
    ref: 'oas/text-block',
    name: 'Text Block',
    description: 'Paragraph / rich text',
    patterns: ['other'],
    props: [{ name: 'text', type: 'binding', required: true }],
  },
  {
    ref: 'oas/image',
    name: 'Image',
    description: 'Single image',
    patterns: ['other'],
    props: [{ name: 'source', type: 'binding', required: true }, { name: 'aspectRatio', type: 'number' }],
  },
  {
    ref: 'oas/media-player',
    name: 'Media Player',
    description: 'Video / audio player',
    patterns: ['video'],
    props: [{ name: 'source', type: 'binding', required: true }],
  },
  {
    ref: 'oas/map-view',
    name: 'Map',
    description: 'Map with markers',
    patterns: ['map'],
    props: [{ name: 'markers', type: 'binding' }],
  },
  {
    ref: 'oas/web-view',
    name: 'Web View',
    description: 'Embedded web content',
    patterns: ['other'],
    roles: ['webview'],
    props: [{ name: 'url', type: 'binding', required: true }],
  },
  {
    ref: 'oas/chart',
    name: 'Chart',
    description: 'Line / bar chart',
    patterns: ['chart'],
    props: [{ name: 'series', type: 'binding', required: true }, { name: 'kind', type: 'enum', values: ['line', 'bar', 'pie'], default: 'line' }],
  },
  // ── Forms & input ─────────────────────────────────────────────
  {
    ref: 'oas/form-group',
    name: 'Form Group',
    description: 'Labeled input fields with validation',
    patterns: ['form'],
    roles: ['auth', 'form'],
    props: [
      { name: 'fields', type: 'items', required: true, description: '[{name, label, keyboard, required}]' },
      { name: 'onSubmit', type: 'action' },
    ],
  },
  {
    ref: 'oas/text-input',
    name: 'Text Input',
    description: 'Single-line input',
    patterns: ['input'],
    props: [
      { name: 'label', type: 'string' },
      { name: 'keyboard', type: 'enum', values: ['text', 'email', 'number', 'phone', 'password', 'url'], default: 'text' },
      { name: 'value', type: 'binding' },
    ],
  },
  {
    ref: 'oas/search-bar',
    name: 'Search Bar',
    description: 'Search input with submit',
    patterns: ['input'],
    roles: ['search'],
    props: [{ name: 'placeholder', type: 'string', default: 'Search' }, { name: 'onSearch', type: 'action' }],
  },
  {
    ref: 'oas/picker',
    name: 'Picker',
    description: 'Select from options',
    patterns: ['picker'],
    props: [{ name: 'options', type: 'items', required: true }, { name: 'value', type: 'binding' }],
  },
  {
    ref: 'oas/button-primary',
    name: 'Primary Button',
    description: 'Main call-to-action button',
    patterns: ['button'],
    props: [{ name: 'label', type: 'string', required: true }, onPress],
  },
  {
    ref: 'oas/button-secondary',
    name: 'Secondary Button',
    description: 'Low-emphasis button',
    patterns: ['button'],
    props: [{ name: 'label', type: 'string', required: true }, onPress],
  },
  // ── Commerce ──────────────────────────────────────────────────
  {
    ref: 'oas/cart-item-list',
    name: 'Cart Item List',
    description: 'Cart rows with quantity controls',
    patterns: ['list'],
    roles: ['cart'],
    props: [items, { name: 'onQuantityChange', type: 'action' }, { name: 'onRemove', type: 'action' }],
  },
  {
    ref: 'oas/price-row',
    name: 'Price Row',
    description: 'Label + amount line (subtotal, shipping, total)',
    patterns: ['other'],
    roles: ['cart', 'checkout'],
    props: [
      { name: 'label', type: 'string', required: true },
      { name: 'amount', type: 'binding', required: true },
      { name: 'emphasis', type: 'boolean', default: false },
    ],
  },
  {
    ref: 'oas/checkout-summary',
    name: 'Checkout Summary',
    description: 'Order lines + totals + pay action',
    patterns: ['form', 'list'],
    roles: ['checkout'],
    props: [items, { name: 'onPay', type: 'action' }],
  },
  {
    ref: 'oas/quantity-stepper',
    name: 'Quantity Stepper',
    description: '− / + numeric stepper',
    patterns: ['button'],
    roles: ['cart', 'detail'],
    props: [{ name: 'value', type: 'binding', required: true }, { name: 'onChange', type: 'action' }],
  },
  // ── Identity & settings ───────────────────────────────────────
  {
    ref: 'oas/avatar-header',
    name: 'Avatar Header',
    description: 'User avatar + name block',
    patterns: ['card'],
    roles: ['profile'],
    props: [{ name: 'name', type: 'binding' }, { name: 'avatarUrl', type: 'binding' }],
  },
  {
    ref: 'oas/settings-list',
    name: 'Settings List',
    description: 'Grouped settings rows (toggle / link / value)',
    patterns: ['list'],
    roles: ['settings', 'profile'],
    props: [items],
  },
  // ── Feedback ──────────────────────────────────────────────────
  {
    ref: 'oas/dialog',
    name: 'Dialog',
    description: 'Modal confirmation dialog',
    patterns: ['dialog'],
    roles: ['modal'],
    props: [
      { name: 'title', type: 'string', required: true },
      { name: 'message', type: 'string' },
      { name: 'onConfirm', type: 'action' },
      { name: 'onCancel', type: 'action' },
    ],
  },
  {
    ref: 'oas/toast',
    name: 'Toast',
    description: 'Transient notification',
    patterns: ['toast'],
    props: [{ name: 'message', type: 'string', required: true }, { name: 'kind', type: 'enum', values: ['info', 'success', 'error'], default: 'info' }],
  },
  {
    ref: 'oas/empty-state',
    name: 'Empty State',
    description: 'Placeholder for empty collections',
    patterns: ['empty'],
    props: [{ name: 'message', type: 'string', required: true }, { name: 'actionLabel', type: 'string' }, onPress],
  },
  {
    ref: 'oas/skeleton',
    name: 'Skeleton',
    description: 'Loading shimmer placeholder',
    patterns: ['empty'],
    props: [{ name: 'lines', type: 'number', default: 3 }],
  },
];
