import { readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { AppSpec } from '@oas/app-spec';
import type { InteractionFlowGraph } from '@oas/flow-graph';
import { e2eFlows } from './e2e.js';
import { componentName as componentNameOf } from './props.js';
import { appDataFile, appJson, indexFile, layoutFile, packageJson, tsconfigJson } from './project-files.js';
import { screenFile } from './screens.js';

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GenerateOptions {
  /** Source graph — enables e2e flow generation. */
  ifg?: InteractionFlowGraph;
  /** AI-generated components referenced by the spec (ref → implementation). */
  customComponents?: Array<{ ref: string; tsx: string }>;
}

/**
 * App Spec → a complete, standalone Expo project (expo-router, TypeScript).
 * Deterministic: same spec → byte-identical output. The result is normal
 * React Native code — no player shell, no runtime dependency on OAS.
 */
export function generateProject(spec: AppSpec, opts: GenerateOptions = {}): GeneratedFile[] {
  const customRefs = new Set((opts.customComponents ?? []).map((c) => c.ref));
  const usedRefs = new Set(spec.screens.flatMap((s) => s.components.map((c) => c.ref)));

  const files: GeneratedFile[] = [
    { path: 'package.json', content: packageJson(spec) },
    { path: 'app.json', content: appJson(spec) },
    { path: 'tsconfig.json', content: tsconfigJson() },
    { path: '.gitignore', content: 'node_modules/\n.expo/\ndist/\n*.log\n' },
    { path: 'app/_layout.tsx', content: layoutFile(spec) },
    { path: 'app/index.tsx', content: indexFile(spec) },
    ...spec.screens.map((s) => ({ path: `app/${s.id}.tsx`, content: screenFile(s, customRefs) })),
    { path: 'components/oas.tsx', content: template('oas-components.tsx') },
    { path: 'theme/tokens.ts', content: template('theme-tokens.ts') },
    { path: 'state/app-data.ts', content: appDataFile(spec) },
    { path: 'README.md', content: readme(spec) },
  ];

  for (const custom of opts.customComponents ?? []) {
    if (!usedRefs.has(custom.ref)) continue;
    files.push({ path: `components/custom/${componentNameOf(custom.ref)}.tsx`, content: fixCustomImports(custom.tsx) });
  }

  if (opts.ifg) {
    for (const [name, yaml] of e2eFlows(spec, opts.ifg)) {
      files.push({ path: `e2e/${name}`, content: yaml });
    }
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/** Custom components are authored against '../theme/tokens'; from components/custom/ it's two levels up. */
function fixCustomImports(tsx: string): string {
  return tsx.replace(/from '\.\.\/theme\/tokens'/g, `from '../../theme/tokens'`);
}

export async function writeProject(files: GeneratedFile[], outDir: string): Promise<void> {
  for (const file of files) {
    const full = join(outDir, file.path);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, file.content);
  }
}

function template(name: string): string {
  return readFileSync(new URL(`../templates/${name}`, import.meta.url), 'utf8');
}

function readme(spec: AppSpec): string {
  return `# ${spec.app.name}

Generated by [Open App Studio](https://github.com/squarezw/open-app-studio)${
    spec.meta?.sourceStoreUrl ? ` from the interaction structure of ${spec.meta.sourceStoreUrl}` : ''
  }.

\`\`\`bash
npm install
npx expo start          # then press a (Android) or i (iOS simulator)
npm run typecheck
maestro test e2e/       # replay the cloned user flows as acceptance tests
\`\`\`

- Screens live in \`app/\` (expo-router), blocks in \`components/oas.tsx\`, demo data in \`state/app-data.ts\`.
- This is your code now — no Open App Studio runtime, edit anything.
- Note: this app reproduces *interaction structure*, not the original's assets or content. Make it yours before shipping (App Store Review 4.1 / Play impersonation policies).
`;
}
