/** Theme tokens — generated by @oas/codegen. Tune to make the app yours. */
export const colors = {
  bg: '#0e1116',
  panel: '#171c26',
  border: '#2a3347',
  text: '#e6ecf5',
  muted: '#8b9cbd',
  accent: '#4f7df9',
  onAccent: '#ffffff',
  success: '#3ecf8e',
  danger: '#ff5370',
};

export const spacing = { xs: 4, sm: 8, md: 14, lg: 22, xl: 36 };

export const radii = { sm: 6, md: 10, lg: 16 };
